name: Release

on:
  push:
    tags:
      - 'v*' # Trigger saat tag dengan format v* dipush

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # Sesuaikan dengan versi Go yang digunakan

      - name: Build
        run: go build -o substorm .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            substorm
          generate_release_notes: true